config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "/user_profile", to: "profiles#show"
  
  resources :topics do
    resources :posts do
      resources :comments do
        resources :commentsratings
      end
      resources :tags
      resources :ratings
    end
    post "/posts/:post_id/read/:user_id", to: "posts#read"
    resources :tags
  end

  resources :posts
  post "/posts/filter", to: "posts#filter"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "topics#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :name, :description, presence: true 
    has_many :posts,dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_path, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>" >
  <div class="d-flex border border-1 justify-content-center align-items-center fw-bold fs-1" style="min-height:10rem;word-break:break-all;box-shadow:0px 0px 10px 2px black inset;">
    <%= topic.name %>
  </div>

  <div class="text-start fs-5" style="word-break:break-all;">
    <div class="fw-bold fs-6">Description</div>
    <%= topic.description %>
  </div>

  <div class="text-end" style="width:100%;font-size:15px;">Posts: <b><%= topic.posts.count %></b></div>

</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<%if notice%>
  <p class="my-2 alert alert-success w-50 mx-auto"><%= notice %></p>
<%end%>

<div class="d-flex">
  <h1 class="display-5 fw-bold">Topics</h1>
    <a href="<%= new_topic_path%>" class="ms-auto fs-1">
      <i class="bi bi-plus-circle-fill text-dark">
      </i>
    </a>
</div>

<div class="d-flex my-3" style="gap:1rem;flex-wrap: wrap;">
  <% @topics.each do |topic| %>
    <div class="card bg-secondary border border-dark border-1 text-light" style="width:23.5%;box-shadow:0px 0px 10px 3px black">
      <div class="card-body">
        <h5 class="card-title"><%= topic.name %></h5>
        <p class="card-text"><%= topic.description %></p>
        <div class="d-flex justify-content-around">
          <%= link_to "view", topic ,class: "btn btn-primary"%>
          <a href="<%= edit_topic_path(topic)%>" class="border border-1 border-info px-3 rounded"><i class="bi bi-vector-pen text-dark fs-4"></i></a>
          <%= button_to "", topic_path(topic) ,method: :delete,class: "bi bi-trash3-fill border-0 bg-transparent text-danger fs-4" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<%if notice%>
  <p class="my-2 alert alert-success w-50 mx-auto"><%= notice %></p>
<%end%>
<div class="d-flex">
  <a href="<%= topics_path%>"><i class="bi bi-arrow-left-circle-fill fs-1 text-dark"></i></a>
  <div class="ms-auto d-flex">
    <a href="<%= edit_topic_path(@topic)%>" class="m-3 py-0 rounded-circle btn btn-outline-dark"><i class=" bi bi-vector-pen fs-3"></i></a>
    <%= button_to "", @topic ,method: :delete,class: "m-3 py-0 rounded-circle btn btn-outline-danger bi bi-trash3-fill fs-3" %>
  </div>
</div>

<div class="fs-4 text-center border border-dark border-1 rounded p-3 w-50 m-auto" style="box-shadow:0px 0px 5px 2px black;">
  <%= render @topic %>
</div>

<div class="position-absolute" style="bottom:3rem;right:3rem;">
  <a href="<%= topic_posts_path(@topic)%>" class="m-3"><i class="bi bi-arrow-right-circle-fill text-success display-4"></i></a>
</div>