config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "/user_profile", to: "profiles#show"
  
  resources :topics do
    resources :posts do
      resources :comments do
        resources :commentsratings
      end
      resources :tags
      resources :ratings
    end
    post "/posts/:post_id/read/:user_id", to: "posts#read"
    resources :tags
  end

  resources :posts
  post "/posts/filter", to: "posts#filter"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "topics#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :posts_tag, dependent: :destroy
    has_many :posts, through: :posts_tag
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_topic, only: %i[ index new create show edit update destroy ]
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    unless params[:post_id].nil?
      @post=Post.find(params[:post_id])
    end
    @tag = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
    unless params[:post_id].nil?
      @post=Post.find(params[:post_id])
    end
  end

  # GET /tags/new
  def new
    unless params[:post_id].nil?
      @post=Post.find(params[:post_id])
    end
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
    unless params[:post_id].nil?
      @post=Post.find(params[:post_id])
    end
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        if params[:post_id].nil?
          format.html { redirect_to new_topic_post_path(@topic), notice: "Tag was successfully created." }
        else
          @post=Post.find(params[:post_id])
          format.html { redirect_to edit_topic_post_path(@topic,@post), notice: "Tag was successfully created." }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        if params[:post_id].nil?
          format.html { redirect_to topic_tags_path(@topic), notice: "Tag was successfully updated." }
        else
          @post=Post.find(params[:post_id])
          format.html { redirect_to topic_post_tags_path(@topic,@post), notice: "Tag was successfully updated." }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy

    if params[:post_id].nil?
      @tag.destroy
    else
      @post=Post.find(params[:post_id])
      @post.tags.delete(@tag)
    end

    respond_to do |format|
      if params[:post_id].nil?
        format.html { redirect_to topic_tags_path(@topic), notice: "Tag was successfully destroyed." }
      else
        format.html { redirect_to topic_post_tags_path(@topic,@post), notice: "Tag was successfully destroyed." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<h1>Editing tag</h1>
<%if @post.nil?%>
  <%= form_with(model: [@topic,@tag]) do |form| %>
    <% if @tag.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
          <% @tag.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<%else%>
  <%= form_with(model: [@topic,@post,@tag]) do |form| %>
    <% if @tag.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
          <% @tag.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<%end%>

<br>

<div>
  <%if @post.nil?%>
    <%= link_to "Show", topic_tag_path(@topic,@tag) %> |
    <%= link_to "Back", topic_tags_path(@topic) %>
  <%else%>
    <%= link_to "Show", topic_post_tag_path(@topic,@post,@tag) %> |
    <%= link_to "Back", topic_post_tags_path(@topic,@post) %>
  <%end%>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All Tags</h1>

<div id="tags">
<table>
  <thead>
    <th>Tag name</th>
    <th colspan="3">Operations</th>
  </thead>
  <tbody>
    <% @tag.each do |tag| %>
      <tr>
        <td><%= tag.name%></td>
        <%if @post.nil?%>
          <td><%= link_to "Show ", topic_tag_path(@topic,tag) %></td>
          <td><%= link_to "Edit", edit_topic_tag_path(@topic,tag) %></td>
          <td><%= button_to "Delete", topic_tag_path(@topic,tag),method: :delete %></td>
        <%else%>
          <td><%= link_to "Show ", topic_post_tag_path(@topic,@post,tag) %></td>
          <td><%= link_to "Edit", edit_topic_post_tag_path(@topic,@post,tag) %></td>
          <td><%= button_to "Delete", topic_post_tag_path(@topic,@post,tag),method: :delete %></td>
        <%end%>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%if @post.nil?%>
  <%= link_to "New tag", new_topic_tag_path(@topic) %> |
  <%= link_to "Back", new_topic_post_path(@topic) %>
<%else%>
  <%= link_to "New tag", new_topic_post_tag_path(@topic,@post) %> |
  <%= link_to "Back", edit_topic_post_path(@topic,@post) %>
<%end%>

app/views/tags/new.html.erb
<h1>New tag</h1>
<%if @post.nil?%>
  <%= form_with(model: [@topic,@tag]) do |form| %>
    <% if @tag.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
          <% @tag.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<%else%>
  <%= form_with(model: [@topic,@post,@tag]) do |form| %>
    <% if @tag.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
          <% @tag.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<%end%>

<br>

<div>
  <%if @post.nil?%>
    <%= link_to "Back", new_topic_post_path(@topic) %>
  <%else%>
    <%= link_to "Back", edit_topic_post_path(@topic,@post) %>
  <%end%>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <h4>Tag name</h4>
  <p><%= @tag.name%></p>
</div>

<div>
  <%if @post.nil?%>
    <%= link_to "Edit", edit_topic_tag_path(@topic,@tag) %> |
    <%= link_to "Back", topic_tags_path(@topic) %>
    <%= button_to "Destroy", topic_tag_path(@topic,@tag), method: :delete %>
  <%else%>
    <%= link_to "Edit", edit_topic_post_tag_path(@topic,@post,@tag) %> |
    <%= link_to "Back", topic_post_tags_path(@topic,@post) %>
    <%= button_to "Destroy", topic_post_tag_path(@topic,@post,@tag), method: :delete %>
  <%end%>
</div>