config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "/user_profile", to: "profiles#show"
  
  resources :topics do
    resources :posts do
      resources :comments do
        resources :commentsratings
      end
      resources :tags
      resources :ratings
    end
    post "/posts/:post_id/read/:user_id", to: "posts#read"
    resources :tags
  end

  resources :posts
  post "/posts/filter", to: "posts#filter"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "topics#index"
end

app/models/post.rb
class Post < ApplicationRecord
  scope :filtered, ->(from,to) {where("created_at between ? and ?",from,to.to_date + 1.day)}

  validates :name, length: {maximum: 20}
  validates :name , :description, presence: true

  has_one_attached :post_profile 
  
  paginates_per 10
  has_many :comments, dependent: :destroy
  belongs_to :topic

  has_many :posts_tag, dependent: :destroy
  has_many :tags, through: :posts_tag

  has_many :ratings, dependent: :destroy

  belongs_to :user

  has_and_belongs_to_many :users

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  protect_from_forgery with: :null_session
  before_action :set_post, only: %i[ show edit update destroy ]

  def index

    if params[:topic_id].nil?
      @post = Post.includes([:topic,:user,:post_profile_attachment]).all.page(params[:page])
    else
      @topic = Topic.find(params[:topic_id])
      @post = @topic.posts.includes(:user,:post_profile_attachment).all
    end

  end

  def new
    @tag=Tag.all
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end
  
  def filter
    from=params[:from_date]=="" ? Date.yesterday : params[:from_date];
    to=params[:to_date]=="" ? Date.today : params[:to_date];
    puts from
    puts to

    @post = Post.filtered(from,to)
  end

  def read
    post=Post.find(params[:post_id])
    puts "stage 1"
    if post.users.where("id=#{params[:user_id]}").count==0
      puts "stage 2"
      user=User.find(params[:user_id])
      post.users << user
      puts "success add"
    end
  end

  def show
    @rating=@post.ratings.group(:no).count
    @star=Rating.new
    @topic = Topic.find(params[:topic_id])
    @comment=@post.comments.all
    @tag=@post.tags.all
    @commentsrating=Commentsrating.new
  end

  def edit
    @tag=Tag.all
    @topic = Topic.find(params[:topic_id])
  end

  def update
    @topic = Topic.find(params[:topic_id])

    respond_to do |format|
      if @post.update(post_params)
        @post.tags.clear
        params[:post][:check].each do |check|
          if check!="0"
            tag=Tag.find(check)
            @post.tags << tag
          end
        end
        format.html { redirect_to topic_post_path(@topic,@post), notice: "post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    puts "check parameters #{params[:post][:tags]}"
    @post = @topic.posts.new(post_params)
    @post.user_id=current_user.id

    respond_to do |format|
      if @post.save
        params[:post][:tags].each do |check|
          if check!="0"
            tag=Tag.find(check)
            @post.tags << tag
          end
        end
        format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully created." }
        format.js
      else
        puts "facing problem"
        format.html { redirect_to new_topic_post_path(@topic), status: :unprocessable_entity,notice: "Post has facing problem." }
        format.js
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :description, :post_profile)
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_display.html.erb
<% @post.each do |post| %>

  <div class="border border-1 p-2 border-dark rounded w-75 mx-auto my-2 bg-dark text-light">
    <div class="d-flex fw-bold fs-5 mb-2">
      <% unless post.users.where("id=#{current_user.id}").count>0 %>
        <i class="bi bi-dot px-2 mt-1 text-success" style="transform:scale(5);"></i>
      <%end%>
      <div><%= post.name %></div>
      <%if @topic.nil?%>
        <div class="ms-auto"><%= post.topic.name %></div>
      <%end%>
      <% if can? :destroy, post%>
      <div class="ms-auto">
        <%= button_to "", topic_post_path(post.topic_id,post) ,method: :delete ,class: "btn btn-outline-danger bi bi-trash3-fill fs-6"%>
      </div>
      <%end%>
    </div>
    <div style="width:90%;" class="mx-auto">
      <%if post.post_profile.attached?%>
        <%= image_tag post.post_profile ,style: "width:100%;"%>
      <%else%>
        <div style="width:100%;height:10rem;background-color:gray;"></div>
      <%end%>
    </div>
    <div class="fs-6 lead p-3" style="word-break:break-all;"><%= post.description %></div>
    <div class="row border border-1 border-bottom-0 border-start-0 border-end-0 border-daark">
      <div class="col lead" style="font-size:13px;">
        Author name:
        <div class="fw-bold" style="font-size:12px;">
          <%= post.user.email %>
        </div>
      </div>

      <div class="col lead" style="font-size:13px;">
        Avarage Rating:
        <div class="fw-bold" style="font-size:12px;">
          <%= post.ratings_average %> Stars 
        </div>
      </div>

      <div class="col lead" style="font-size:13px;">
        Comments Count:
        <div class="fw-bold" style="font-size:12px;">
          <%= post.comments_count %> Comments 
        </div>
      </div>

      <div class="col w-100 d-flex">
        <%= link_to "Open", topic_post_path(post.topic_id,post),class: "btn btn-primary w-50" %>

        <% if can? :update, post%>
          <%= link_to "", edit_topic_post_path(post.topic_id,post),class: "bi bi-vector-pen w-50 fs-4 py-0 rounded btn btn-outline-warning" %>
        <%end%>
        
      </div>
    </div>

  </div>
<%end%>


        
          

app/views/posts/create.js.erb
<% if @post.errors.any? %>
    window.alert('<%= @post.errors.full_messages.join("\n")%>')
<%else%>
    window.alert("Post created Successfully")
<%end%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_with(model: [@topic,@post]) do |form| %>
  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post_profile,"Select post" %><br>
    <%= form.file_field :post_profile %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div style="display:flex;gap:1rem;">
    <% if @tag.count>0%>
      <% @tag.each do |tag|%>
        <div>
          <%=form.check_box :check ,{multiple: true}, tag.id %>
          <%= form.label tag.name %>
        </div>
      <%end%>
    <%end%>
    <%= link_to "Create tag", new_topic_post_tag_path(@topic,@post) %>
    <%= link_to "List tags", topic_post_tags_path(@topic,@post) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back", topic_post_path(@topic,@post) %>
</div>

app/views/posts/filter.js.erb
console.log("ok")
window.alert("ok")
$("#posts").html('<%= j render 'display' %>')

app/views/posts/index.html.erb
  <div class="w-75 mx-auto">
    <%if notice%>
      <p style="color: green"><%= notice %></p>
    <%end%>

    <div class="d-flex">
      <%unless @topic.nil?%>
        <a href="<%= topic_path(@topic)%>"><i class="bi bi-arrow-left-circle-fill fs-1 text-dark"></i></a>
      <%end%>

      <h2  class="pt-2 ps-3">Posts</h2>
      <%unless @topic.nil?%>
        <div class="ms-auto">
          <a href="<%= new_topic_post_path(@topic)%>" class="ms-auto fs-1">
            <i class="bi bi-plus-circle-fill text-dark">
            </i>
          </a>
        </div>
      <%end%>
    </div>

  </div>


  <%if params[:topic_id].nil?%>
    <div class="w-75">
      <div class="ms-auto w-25">
        <%= form_with local: false, url: posts_filter_path() do |form| %>
          <div style="display: flex">
            <div class="form-group">
              <%= form.label :from_date , "From date", class: "form-label" %><br>
              <%= form.date_field :from_date, class: "form-control border border-1 border-dark" %>
            </div>
            <div class="form-group mx-2">
              <%= form.label :to_date , "To date", class: "form-label"  %><br>
              <%= form.date_field :to_date, class: "form-control border border-1 border-dark" %>
            </div>
            <div class="mt-auto">
              <%= form.submit "Filter", class: "btn btn-dark w-100"%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  <%end%>


  <div id="posts">
    <%= render "display"%>
  </div>

  <%if @topic.nil?%>
    <%= paginate @post%>
  <%end%>

app/views/posts/new.html.erb
<style>
  .loader {
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    width: 50px;
    height: 50px;
    -webkit-animation: spin 2s linear infinite; /* Safari */
    animation: spin 2s linear infinite;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
</style>
<div id="loader-panel" style="display:none;">
  <div class="loader"></div>
</div>

<div id="content">

  <p style="color: red"><%= notice %></p>

  <h1>New Post</h1>

  <%= form_for([@topic,@post],remote: true) do |form| %>
    <% if @post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
          <% @post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :post_profile,"Select post" %><br>
      <%= form.file_field :post_profile %>
    </div>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <div style="display:flex;gap:1rem;">
      <% if @tag.count>0%>
        <% @tag.each do |tag|%>
          <div>
            <%=form.check_box :tags ,{multiple: true}, tag.id ,nil%>
            <%= form.label tag.name %>
          </div>
        <%end%>
      <%end%>
      <%= link_to "Create tag", new_topic_tag_path(@topic) %>
      <%= link_to "List tags", topic_tags_path(@topic) %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>

  <br>

  <div>
    <%= link_to "Back to posts", topic_posts_path(@topic) %>
  </div>
</div>

<script>
  $(document).ready(function(){
    console.log("ok")
    $("form").on("ajax:beforeSend",()=>{
      console.log("called")
      $("#loader-panel").css("display","");
      $("#content").css("display","none");

    })

    $("form").on("ajax:complete",()=>{
      console.log("completed")
      $("#loader-panel").css("display","none");
      $("#content").css("display","");
    })

  })
</script>

app/views/posts/show.html.erb
<%if notice%>
  <p class="alert w-50 mx-auto my-2 alert-success p-2" onload="call()" style="color: green"><%= notice %></p>
<%end%>

<div class="d-flex">
  <a href="<%= topic_posts_path(@topic)%>"><i class="bi bi-arrow-left-circle-fill fs-1 text-dark"></i></a>
  <div class="ms-auto d-flex gap-2 mt-2">
    <% if can? :update, @post%>
      <%= link_to "", edit_topic_post_path(@topic,@post), class: "bi bi-vector-pen btn btn-outline-warning fs-5 rounded-circle", style: "height:90%;" %>
    <%end%>

    <% if can? :destroy, @post%>
      <%= button_to "", topic_post_path(@topic,@post), method: :delete, class: "bi bi-trash3-fill btn fs-5 btn-outline-danger rounded-circle" %>
    <%end%>
  </div>
  
</div>

<div class="w-75 mx-auto">
  <div class=" my-2 fs-2 d-flex gap-2 ">
    <div class="fw-bold ">Name:</div>
    <%= @post.name %>
  </div>

  <%if @tag.count>0%>
    <div class="d-flex">
      <%@tag.each do |tag| %>
        <span class="bg-dark text-light m-2 d-flex px-1 rounded" style="font-size:12px;">
          <%= tag.name%>
          <% if can? :destroy, @post%>
            <span><%= button_to "",  topic_post_tag_path(@topic,@post,tag),method: :delete, class: "bi bi-x-lg border-0 bg-transparent text-danger" %></span>
          <%end%>
        </span>
      <%end%>
    </div>
  <%end%>

  <div  class=" my-2">
    <div class="fw-bold " style="font-size:12px;">Description:</div>
    <%= @post.description %>  
  </div>
</div>

<div class="mx-auto" style="width:80%">
  <%if @post.post_profile.attached?%>
    <%= image_tag @post.post_profile ,style: "width:100%;border:1px solid black;padding:5px;"%>
  <%else%>
    <div style="width:100%;height:13rem;background-color:gray;"></div>
  <%end%>
</div>

<div class="w-50 mx-auto my-2">
  <%= form_with(model: [@topic,@post,@star],:html=>{:style=>"display:flex;gap:1rem;"}) do |form|%>

    <div>
      <%=form.radio_button :star,1 %>
      <label class="text-warning">1 <i class="bi bi-star-fill text-warning"></i></label>
      (<%= @rating[1] ? @rating[1] : 0;%>)
    </div>

    <div>
      <%=form.radio_button :star,2%>
      <label class="text-warning">2 <i class="bi bi-star-fill text-warning"></i></label>
      (<%= @rating[2] ? @rating[2] : 0;%>)
    </div>

    <div>
      <%=form.radio_button :star,3%>
      <label class="text-warning">3 <i class="bi bi-star-fill text-warning"></i></label>
      (<%= @rating[3] ? @rating[3] : 0;%>)
    </div>

    <div>
      <%=form.radio_button :star,4%>
      <label class="text-warning">4 <i class="bi bi-star-fill text-warning"></i></label>
      (<%= @rating[4] ? @rating[4] : 0;%>)
    </div>

    <div>
      <%=form.radio_button :star,5%>
      <label class="text-warning">5 <i class="bi bi-star-fill text-warning"></i></label>
      (<%= @rating[5] ? @rating[5] : 0;%>)
    </div>

    <div>
      <%= form.submit "Add #{@post.ratings.average(:no).to_f.truncate(1)}",class: "btn btn-primary py-0"%>
    </div>

  <%end%>
</div>




---------------------------------------------------------------------------------------------------

<h3>Comments</h3>

<div>
  <%= link_to "Add comment", new_topic_post_comment_path(@topic,@post) %>
</div>

<%if @comment.count>0%>
  <table>
    <thead>
      <tr>
        <th>Message</th>
        <th>Author Name</th>
        <% if can? :create, Commentsrating %>
            <th>Set Rating</th>
        <%end%>
        <th colspan="3">Operations</th>
      </tr>
    </thead>
    <tbody>
      <%@comment.each do |comment| %>
        <tr>
          <td><%= comment.msg%></td>
          <td><%= User.find(comment.user_id).email%></td>

          <% if can? :create, Commentsrating %>
            <td>
              <%= form_with(model: [@topic,@post,comment,@commentsrating],:html=>{:style=>"display:flex;gap:1rem;"}) do |form|%>

                <div>
                  <%=form.radio_button :no,1 %>
                  <%=form.label :no, "1 star"%>
                </div>

                <div>
                  <%=form.radio_button :no,2%>
                  <%=form.label :no, "2 star"%>
                </div>

                <div>
                  <%=form.radio_button :no,3%>
                  <%=form.label :no, "3 star"%>
                </div>

                <div>
                  <%=form.radio_button :no,4%>
                  <%=form.label :no, "4 star"%>
                </div>

                <div>
                  <%=form.radio_button :no,5%>
                  <%=form.label :no, "5 star"%>
                </div>

                <div>
                  <%= form.submit "Add"%>
                </div>

              <%end%>
            </td>
          <%end%>

          <td><%= link_to "show", topic_post_comment_path(@topic,@post,comment)%></td>
          
          <% if can? :update, comment%>
            <td><%= link_to "Edit", edit_topic_post_comment_path(@topic,@post,comment)%></td>
          <%end%>

          <% if can? :destroy, comment%>
            <td><%= button_to "Delete", topic_post_comment_path(@topic,@post,comment),method: :delete %></td>
          <%end%>
        </tr>
        
      <%end%>
    </tbody>  
  </table>
<%else%>
  <p>Empty comments</p>
<%end%>

<script>
    console.log("<%=current_user.id%>")
    console.log("<%= topic_post_path%>/read/<%=current_user.id%>")
    var xhttp = new XMLHttpRequest();
    xhttp.open("POST","<%= topic_post_path%>/read/<%=current_user.id%>");
    xhttp.send();
</script>